# Site settings
title: Фронтир
email: marinintim@gmail.com
description: "Журнал про фронтенд-разработку, её будни и праздники."
baseurl: ""
url: "http://frontiermag.ru"

# Build settings
markdown: kramdown
permalink: none
